apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: jumbolpc/springboot-app-jenkins:latest
          resources:
            requests:
              cpu: "250m"
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 250Mi
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 9090 # Expose port 9090
    targetPort: 9090 # Container port 9090
      